### ISSUE TITLE
TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'depth'

### ISSUE THREAD

**Issue by caiduoduo12138** [SwinTransformer/Swin-Transformer-Object-Detection#11]
Traceback (most recent call last):
  File "/home/cai/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'depth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cai/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/cai/project/Swin/mmdet/models/detectors/cascade_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "/home/cai/project/Swin/mmdet/models/detectors/two_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/cai/project/Swin/mmdet/models/builder.py", line 39, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/cai/project/Swin/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/cai/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'depth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/cai/project/Swin/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/cai/project/Swin/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/cai/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'depth'
***********************************************************
When run the demo provided in config, it run well.
However ,When I employ the swintransformer as the backbone in cascade rcnn, error occurs.
Can give me some advice? Thanks.

**Comment by faisalst** [comment]
How did you solve this?
