### ISSUE TITLE
SyntaxError: invalid syntax 'dataset_type': 'CocoDataset' lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'dataset_type'", context=('\n', (148, 0))

### ISSUE THREAD

**Issue by leiqing1** [SwinTransformer/Swin-Transformer-Object-Detection#12]
Traceback (most recent call last):
  File "/opt/python3.7/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 122, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/opt/python3.7/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/opt/python3.7/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/opt/python3.7/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'dataset_type'", context=('\n', (148, 0))

During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 129, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/opt/python3.7/lib/python3.7/site-packages/mmcv/utils/config.py", line 458, in dump
    f.write(self.pretty_text)
  File "/opt/python3.7/lib/python3.7/site-packages/mmcv/utils/config.py", line 413, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/opt/python3.7/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/opt/python3.7/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 128, in ParseCodeToTree
    raise e
  File "/opt/python3.7/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 126, in ParseCodeToTree
    ast.parse(code)
  File "/opt/python3.7/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 148
    'dataset_type': 'CocoDataset'
                 ^
SyntaxError: invalid syntax

我猜应该是环境安装的问题,第一次使用mmdetection和pytorch,不太熟悉,请过来人指点下,谢谢:

**Comment by leiqing1** [comment]
已解决. 是我执行命令有问题.
原错误执行命令: python3.7 tools/train.py ./configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py --cfg-options model.pretrained=./configs/swin/mask_rcnn_swin_tiny_patch4_window7.pth [model.backbone.use_checkpoint=True]
错误原因,是我执行程序时加的' [model.backbone.use_checkpoint=True]'造成的.
加' [model.backbone.use_checkpoint=True]'初衷,第一次用mmdetection,用官网推理模型做pretain-model,一直报错误,以为加了' [model.backbone.use_checkpoint=True]'就可以用inference的模型了.
当然,怎么用inference模型做pretain-model还没有解决.

**Comment by thangnx183** [comment]
i encounter exactly same error. Something is wrong about `'dataset_type': 'CocoDataset'` in `coco_instance.py`. Have you fixed the error yet  @leiqing1  ?

**Comment by thangnx183** [comment]
i tried to install both from docker and conda. Both ways still end up this error

**Comment by leiqing1** [comment]
> i encounter exactly same error. Something is wrong about `'dataset_type': 'CocoDataset'` in config file `coco_instance.py`. Have you fixed the error yet @leiqing1 ?

wrong executive order of my error.

**Comment by thangnx183** [comment]
can you show me detail of your config file ?

**Comment by thangnx183** [comment]
nvm. i just remove `[model.backbone.use_checkpoint=True]` from command, it worked

**Comment by ola0x** [comment]
it worked
