### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group for cascade_mask_rcnn_swin_base_patch4

### ISSUE THREAD

**Issue by rgkannan676** [SwinTransformer/Swin-Transformer-Object-Detection#129]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**

Getting a run time error "RuntimeError: Default process group has not been initialized, please make sure to call init_process_group." when training using below command 
```
python tools/train.py configs/swin/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py --cfg-options model.pretrained=swin_base_patch4_window12_384_22k.pth
```
Error:

```
Traceback (most recent call last):
  File "C:\Users\user\Swin-Transformer-Object-Detection\tools\train.py", line 187, in <module>
    main()
  File "C:\Users\user\Swin-Transformer-Object-Detection\tools\train.py", line 176, in main
    train_detector(
  File "c:\users\user\swin-transformer-object-detection\mmdet\apis\train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\detectors\base.py", line 247, in train_step
    losses = self(**data)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\detectors\base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\detectors\two_stage.py", line 161, in forward_train
    roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list,
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\roi_heads\cascade_roi_head.py", line 257, in forward_train
    bbox_results = self._bbox_forward_train(i, x, sampling_results,
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\roi_heads\cascade_roi_head.py", line 157, in _bbox_forward_train
    bbox_results = self._bbox_forward(stage, x, rois)
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\roi_heads\cascade_roi_head.py", line 147, in _bbox_forward
    cls_score, bbox_pred = bbox_head(bbox_feats)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\user\swin-transformer-object-detection\mmdet\models\roi_heads\bbox_heads\convfc_bbox_head.py", line 139, in forward
    x = conv(x)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\mmcv\cnn\bricks\conv_module.py", line 203, in forward
    x = self.norm(x)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\nn\modules\batchnorm.py", line 732, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\distributed\distributed_c10d.py", line 845, in get_world_size
    return _get_group_size(group)
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\distributed\distributed_c10d.py", line 306, in _get_group_size
    default_pg = _get_default_group()
  File "C:\Users\user\anaconda3\envs\py_env\lib\site-packages\torch\distributed\distributed_c10d.py", line 410, in _get_default_group

```

**Reproduction**

Training with single GPU
```
python tools/train.py configs/swin/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py --cfg-options model.pretrained=swin_base_patch4_window12_384_22k.pth
```
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Changed the number of classes in configs to 2 classes

3. What dataset did you use?

Custom coco dataset

**Environment**

OS : Windows 10
Torch: 1.1.0
MMCV: 1.4.0

Please advise. Thanks.

**Comment by rgkannan676** [comment]
I am running in windows 10,  so is not able to use 'tools/dist_train.sh' and have installed latest torch and mmcv-full.

**Comment by impiga** [comment]
Thanks for your interest!

We use `SyncBN`  in the bbox head by default. However, it is not compatible with single-gpu training.

You can use `BN` instead. Just modify Line 36, 55, 74 from
```
norm_cfg=dict(type='SyncBN', requires_grad=True)
```
to
```
norm_cfg=dict(type='BN', requires_grad=True)
```

**Comment by rgkannan676** [comment]
Hi @impiga,

 This resolved the issue for me. Thanks.

**Comment by zxf29** [comment]
I met the same problem and tried the solution you mentioned, but the same problem still appeared
