### ISSUE TITLE
Getting error : AttributeError: 'AmpState' object has no attribute 'loss_scalers' in windows while saving checkpoint in training.

### ISSUE THREAD

**Issue by rgkannan676** [SwinTransformer/Swin-Transformer-Object-Detection#130]
Thanks for your work.

**Describe the bug**
I tried to train both 'CascadeMask-RCNN - Swin-B' and 'Mask-RCNN - Swin-S' for a custom COCO dataset in Windows 10'. Got the error below message when it tries to save checkpoint after Epoch 1 

```
File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\apex\amp\frontend.py", line 365, in state_dict
    for idx, loss_scaler in enumerate(_amp_state.loss_scalers):
AttributeError: 'AmpState' object has no attribute 'loss_scalers'
```

**Reproduction**

Ran the following train commands

```
python tools/train.py configs/swin/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py --cfg-options model.pretrained=swin_base_patch4_window12_384_22k.pth
```
```
python tools/train.py configs/swin/mask_rcnn_swin_small_patch4_window7_mstrain_480-800_adamw_3x_coco.py --cfg-options model.pretrained=swin_small_patch4_window7_224.pth
```
Both above commands fails when saving the checkpoint of the first epoch. Error message is 

```
2021-12-23 11:52:49,395 - mmdet - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "C:\Users\users\Swin-Transformer-Object-Detection\tools\train.py", line 187, in <module>
    main()
  File "C:\Users\users\Swin-Transformer-Object-Detection\tools\train.py", line 176, in main
    train_detector(
  File "c:\users\users\swin-transformer-object-detection\mmdet\apis\train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\hooks\checkpoint.py", line 116, in after_train_epoch
    self._save_checkpoint(runner)
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\dist_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\mmcv\runner\hooks\checkpoint.py", line 121, in _save_checkpoint
    runner.save_checkpoint(
  File "c:\users\users\swin-transformer-object-detection\mmcv_custom\runner\epoch_based_runner.py", line 60, in save_checkpoint
    save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
  File "c:\users\users\swin-transformer-object-detection\mmcv_custom\runner\checkpoint.py", line 58, in save_checkpoint
    checkpoint['amp'] = apex.amp.state_dict()
  File "C:\Users\users\anaconda3\envs\py_env\lib\site-packages\apex\amp\frontend.py", line 365, in state_dict
    for idx, loss_scaler in enumerate(_amp_state.loss_scalers):
AttributeError: 'AmpState' object has no attribute 'loss_scalers'

```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

Made changes for Class_number of  custom dataset

3. What dataset did you use?

COCO

**Environment**

OS : Windows 10
Torch: 1.1.0
MMCV: 1.4.0
apex :  installed using the command - 'pip install -v --no-cache-dir .'  (suggested in https://github.com/NVIDIA/apex for Windows)

Please advise. Thanks.

**Comment by rgkannan676** [comment]
The issue is resolved after disabling the apex as suggested in 'https://github.com/SwinTransformer/Swin-Transformer-Object-Detection#apex-optional' . 

1) comment out the code block in the configuration files
2) changed runner = dict(type='EpochBasedRunner', max_epochs=36).
