### ISSUE TITLE
load data list index out of range

### ISSUE THREAD

**Issue by cheng-yue-cpu** [SwinTransformer/Swin-Transformer-Object-Detection#142]
2022-02-09 10:43:22,910 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
2022-02-09 10:43:22,910 - mmdet - INFO - Checkpoints will be saved to /home/augustine.cheng/Swin-Transformer-Object-Detection-master/work_dirs/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco by HardDiskBackend.
Traceback (most recent call last):
  File "./tools/train.py", line 187, in <module>
    main()
  File "./tools/train.py", line 183, in main
    meta=meta)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/apis/train.py",line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47,in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/custom.py", line 193, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/custom.py", line 216, in prepare_train_img
    return self.pipeline(results)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 371, in __call__
    results = self._load_masks(results)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 323, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 323, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/augustine.cheng/anaconda3/envs/swin/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 279, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range

**Comment by THEBEST-cloud** [comment]
Did you solve this problem please?

**Comment by muyoucun** [comment]
+1 请问怎么解决呢？

**Comment by sunhao97** [comment]
Did you solve this problem?

**Comment by sunhao97** [comment]
因为你的segmentation key为[]所以导致这个问题

**Comment by funnymean** [comment]
> 因为你的segmentation key为[]所以导致这个问题

请问该如何解决呢？期待大佬答疑

**Comment by thelandord** [comment]
> > 因为你的segmentation key为[]所以导致这个问题
> 
> 请问该如何解决呢？期待大佬答疑

请问有解决吗
