### ISSUE TITLE
Import file problem when using python tools/test.py command

### ISSUE THREAD

**Issue by zhangxiwensjtu** [SwinTransformer/Swin-Transformer-Object-Detection#143]
**Describe the issue**

I am implementing the Swin-T model on my own dataset. There are two ways for me to run the test code.
- `python tools/test.py configs/swin/cell.py /lustre/home/acct-medcb/medcb-cb1/zxw/project/Swin-Transformer-Object-Detection/work_dirs/cell/epoch_36.pth 2 --eval mAP`
- `tools/dist_test.sh configs/swin/cell.py /lustre/home/acct-medcb/medcb-cb1/zxw/project/Swin-Transformer-Object-Detection/work_dirs/cell/epoch_36.pth 2 --eval mAP`

when I use the second command ,everything goes on well, but when I use the first command, such error occurs :
`
Traceback (most recent call last):
  File "tools/test.py", line 222, in <module>
    main()
  File "tools/test.py", line 165, in main
    dataset = build_dataset(cfg.data.test)
  File "/lustre/home/acct-medcb/medcb-cb1/.conda/envs/Swin/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/lustre/home/acct-medcb/medcb-cb1/.conda/envs/Swin/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'CELLDataset is not in the dataset registry'
`
However , I have already registered my own dataset as CELLDataset, I checked my code and find the problem, when I use the `python tools/test.py` command, it import functions or modules from my conda environment instead of import just from the code itself.
For example ,I hope I can import function `build_dataset` from `./mmdet/datasets/builder`, and I import it using code `from mmdet.datasets import (build_dataloader, build_dataset, replace_ImageToTensor)`. However, it import this function from path  `/lustre/home/acct-medcb/medcb-cb1/.conda/envs/Swin/lib/python3.7/site-packages/mmdet/datasets/builder.py`, which is in my conda environment. And I registered `CELLDataset` in the python file under `mmdet/datasets/` ,not under `/lustre/home/acct-medcb/medcb-cb1/.conda/envs/Swin/lib/python3.7/site-packages/mmdet/datasets/` .

How can I tell the code I want to import function from files under my project instead of site-packages in conda env?
And why tools/dist_test.sh command didn't encounter such problem?

**Comment by maxisawesome** [comment]
Howdy - we're facing this exact same issue. We need mmdet to look at the registry from within Swin-Transformers, but it only looks at the "official" registry in our conda file. Thus, our custom dataset never gets registered and an error gets thrown. We've added the necessary code to the `__init__.py` file as well as the python dataset file, but still no luck. How to resolve the alternative mmdet version that lies within the Swin-Transformers repo seems to be the way to fix this, but we've yet to figure that out. Would love some other ideas!

```
Traceback (most recent call last):
  File "src/libs/Swin-Transformer-Object-Detection/tools/train.py", line 211, in <module>
    main()
  File "src/libs/Swin-Transformer-Object-Detection/tools/train.py", line 186, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'TrexDataset is not in the dataset registry'
ERROR: 1
```

**Comment by maxisawesome** [comment]
I solved this - the key was not installing mmdet _at all_, and instead running `python setup.py develop` and letting that do the mmdet installation (there's code in there to pick up your custom files). This included removing it from my requirements.txt file.
Notably, somewhere else I saw the recommendation of `pip install -r requirements/build.txt` and then `python setup.py develop` to install Swin-Transformers requriements. I removed `pip install -r requirements/build.txt` and got my custom dataset working.

I'm using docker. My final dockerfile looked like the following. Note the custom stuff around copying requirements might not apply to you. Note that Swin-Transformer-Object-Detection is already under `src/libs/Swin-Transformer-Object-Detection` with the custom code in place before this happens. It gets copied in the `COPY . .`.

```
FROM rayproject/ray-ml:bf3eaa-py37-gpu

WORKDIR /workspace

COPY requirements.txt .

RUN pip install --upgrade pip

RUN sudo apt-get -y install libboost-filesystem-dev libboost-dev
RUN pip install openmim
RUN mim install mmcv-full==1.3.17

RUN pip install timm==0.3.2 tensorboardX six 

RUN pip install -r requirements.txt
RUN sudo chown -R ray /workspace
COPY . .
RUN cd src/libs/apex && python setup.py install && cd /workspace
RUN cd src/libs/Swin-Transformer-Object-Detection && python setup.py develop && cd /workspace
```

If you've never used docker and don't know wtf is going on there it's probably something like this:  
``` 
pip install openmim
mim install mmcv-full==1.3.17

pip install timm==0.3.2 tensorboardX six 
cd src/libs/apex && python setup.py install && cd /workspace
cd src/libs/Swin-Transformer-Object-Detection && python setup.py develop && cd /workspace
```
