### ISSUE TITLE
RuntimeError: trying to initialize the default process group twice!

### ISSUE THREAD

**Issue by lilin1234567** [SwinTransformer/Swin-Transformer-Object-Detection#150]
`Traceback (most recent call last):  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 123, in main    init_dist(args.launcher, **cfg.dist_params)  File "/data/lilin/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist    _init_dist_pytorch(backend, **kwargs)  File "/data/lilin/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 32, in _init_dist_pytorch    dist.init_process_group(backend=backend, **kwargs)
  File "/data/lilin/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 388, in init_process_group
    raise RuntimeError("trying to initialize the default process group "
RuntimeError: trying to initialize the default process group twice!
`

**Comment by lilin1234567** [comment]
It’s solved!

**Comment by adverbial03** [comment]
please tell me how to solve the problem,thank you

**Comment by adverbial03** [comment]
> It’s solved!

please tell me how to solve the problem,thank you
