### ISSUE TITLE
KeyError: 'EpochBasedRunnerAmp is not in the runner registry'

### ISSUE THREAD

**Issue by Chenguang-Wang** [SwinTransformer/Swin-Transformer-Object-Detection#158]
Great work!
When I attempted to run the code, I met such error!
Can someone help me?

fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "C:\Users\1\anaconda3\envs\cocodetection\lib\site-packages\mmdet\apis\train.py", line 147, in train_detector
    meta=meta))
  File "C:\Users\1\anaconda3\envs\cocodetection\lib\site-packages\mmcv\runner\builder.py", line 23, in build_runner
    runner = runner_constructor()
  File "C:\Users\1\anaconda3\envs\cocodetection\lib\site-packages\mmcv\runner\default_constructor.py", line 44, in __call__
    return RUNNERS.build(self.runner_cfg, default_args=self.default_args)
  File "C:\Users\1\anaconda3\envs\cocodetection\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "C:\Users\1\anaconda3\envs\cocodetection\lib\site-packages\mmcv\utils\registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'EpochBasedRunnerAmp is not in the runner registry'

**Comment by mastash3ff** [comment]
Perhaps changing the config to reflect "EpochBasedRunner" instead of "EpochBasedRunnerAmp" may help

**Comment by suflaj** [comment]
This is because you haven't installed this repository's mmdet. You can do that by positioning to its root, and then doing `pip install -v -e . `. Also, like it was mentioned, you can just remove the `Amp` part to use mmdet's default `EpochBasedRunner`
