### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker.

### ISSUE THREAD

**Issue by TfeiSong** [SwinTransformer/Swin-Transformer-Object-Detection#16]
在运行中出现以下错误。
2021-04-21 19:29:24,344 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/ASRRW_1/songtengfei/software/anaconda3_swin/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 109760) is killed by signal: Segmentation fault.

**Comment by venje-zhu** [comment]
请问你是怎样解决的？我换了数据集就没事了，怀疑是数据的问题，可我正负样本的数量是相同的，不晓得咋解决
