### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rpn'

### ISSUE THREAD

**Issue by 7xkxkckAnn** [SwinTransformer/Swin-Transformer-Object-Detection#164]
Traceback (most recent call last):
  File "/data/xyz/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/data/xyz/code/Swin-Transformer-Object-Detection-master/mmdet/models/detectors/mask_rcnn.py", line 17, in __init__
    super(MaskRCNN, self).__init__(
  File "/data/xyz/code/Swin-Transformer-Object-Detection-master/mmdet/models/detectors/two_stage.py", line 34, in __init__
    rpn_head_.update(train_cfg=rpn_train_cfg, test_cfg=test_cfg.rpn)
AttributeError: 'NoneType' object has no attribute 'rpn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 158, in main
    model = build_detector(
  File "/data/xyz/code/Swin-Transformer-Object-Detection-master/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/data/xyz/code/Swin-Transformer-Object-Detection-master/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/data/xyz/anaconda3/envs/swin/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: MaskRCNN: 'NoneType' object has no attribute 'rpn'

**Comment by xinsuileya** [comment]
Excuse me, have you solved this problem?
