### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

### ISSUE THREAD

**Issue by xc012** [SwinTransformer/Swin-Transformer-Object-Detection#201]
**Problem**: The error “apex is not installed” during training, but it has been tried to install in various ways, including direct "pip install apex" and download source code and compilation.

**Command**:  python tools/train.py configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py

**Error**：
apex is not installed
Traceback (most recent call last):
  File "tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/datasets/__init__.py", line 10, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/datasets/utils.py", line 9, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/models/backbones/__init__.py", line 13, in <module>
    from .swin_transformer import SwinTransformer
  File "/root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection/mmdet/models/backbones/swin_transformer.py", line 13, in <module>
    from timm.models.layers import DropPath, to_2tuple, trunc_normal_
  File "/root/.local/lib/python3.7/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/root/.local/lib/python3.7/site-packages/timm/models/__init__.py", line 1, in <module>
    from .beit import *
  File "/root/.local/lib/python3.7/site-packages/timm/models/beit.py", line 49, in <module>
    from timm.data import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
  File "/root/.local/lib/python3.7/site-packages/timm/data/__init__.py", line 5, in <module>
    from .dataset import ImageDataset, IterableImageDataset, AugMixDataset
  File "/root/.local/lib/python3.7/site-packages/timm/data/dataset.py", line 12, in <module>
    from .parsers import create_parser
  File "/root/.local/lib/python3.7/site-packages/timm/data/parsers/__init__.py", line 1, in <module>
    from .parser_factory import create_parser
  File "/root/.local/lib/python3.7/site-packages/timm/data/parsers/parser_factory.py", line 3, in <module>
    from .parser_image_folder import ParserImageFolder
  File "/root/.local/lib/python3.7/site-packages/timm/data/parsers/parser_image_folder.py", line 11, in <module>
    from timm.utils.misc import natural_key
  File "/root/.local/lib/python3.7/site-packages/timm/utils/__init__.py", line 4, in <module>
    from .cuda import ApexScaler, NativeScaler
  File "/root/.local/lib/python3.7/site-packages/timm/utils/cuda.py", line 8, in <module>
    from apex import amp
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/pipeline_parallel/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/pipeline_parallel/schedules/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/pipeline_parallel/schedules/fwd_bwd_no_pipelining.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/pipeline_parallel/schedules/common.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/pipeline_parallel/p2p_communication.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/opt/conda/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/transformer/utils.py", line 11, in <module>
AttributeError: module 'torch.distributed' has no attribute '_all_gather_base'

**Environment**：
Python 3.7.6
torch 1.7.1+cu110         
torchaudio 0.7.2               
torchvision 0.8.2+cu110   
apex 0.1
mmcv-full 1.2.4               
mmdet 2.11.0              /root/Swin-Transformer-Object-Detection-master/Swin-Transformer-Object-Detection

**Installation method**:
Apex Installation method: 
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir ./

MMCV Installation method: 
pip install mmcv-full==1.2.4 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7/index.html

mmdet Installation method: 
git clone https://github.com/SwinTransformer/Swin-Transformer-Object-Detection.git
cd Swin-Transformer-Object-Detection
python setup.py develop

**Comment by f2367976412** [comment]
I also encountered the same problem, please tell me if you solved it

**Comment by JankinHou** [comment]
我也遇到了同样的问题，请问最终解决了吗？
