### ISSUE TITLE
Checkpoint Save error in google colab 

### ISSUE THREAD

**Issue by Atul997** [SwinTransformer/Swin-Transformer-Object-Detection#45]
During training when checkpoint was about to save after some epoch not after every epoch the following error is coming up 

```
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/content/drive/My Drive/Swin-Transformer-Object-Detection/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/checkpoint.py", line 69, in after_train_epoch
    self._save_checkpoint(runner)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/dist_utils.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/checkpoint.py", line 75, in _save_checkpoint
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "/content/drive/My Drive/Swin-Transformer-Object-Detection/mmcv_custom/runner/epoch_based_runner.py", line 60, in save_checkpoint
    save_checkpoint(self.model, filepath, optimizer=optimizer, meta=meta)
  File "/content/drive/My Drive/Swin-Transformer-Object-Detection/mmcv_custom/runner/checkpoint.py", line 58, in save_checkpoint
    checkpoint['amp'] = apex.amp.state_dict()
AttributeError: module 'apex' has no attribute 'amp'
```

**Comment by ngfuong** [comment]
I experienced the same problem although I had commented out the apex block of code in the config file was enough
