### ISSUE TITLE
when i run python tools/train.py configs/swin/cascade_mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_1x_coco.py --cfg-options model.pretrained=./cascade_mask_rcnn_swin_tiny_patch4_window7_1x.pth,error  appear

### ISSUE THREAD

**Issue by Bin-ze** [SwinTransformer/Swin-Transformer-Object-Detection#57]
following： 
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/liuguangcan/mmdetection/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'pretrained
could you tell me how can i serve it?

**Comment by ffletcherr** [comment]
Add : `load_from = ./cascade_mask_rcnn_swin_tiny_patch4_window7_1x.pth`  at the end of config file instead of using `--cfg-options model.pretrained=...` as argument.

**Comment by impiga** [comment]
Hi, @Bin-ze . Could you post the config file? 

Also, as @ffletcherr pointed out, `cascade_mask_rcnn_swin_tiny_patch4_window7_1x.pth` is a model finetuned on COCO. If you means to load this weight for initialization, use `load_from` instead of `model.pretrained`. 
(`load_from` loads weight of the whole model, while `model.pretrained` only loads the weight of backbone.)

**Comment by jiabeiwangTJU** [comment]
TypeError: __init__() got an unexpected keyword argument 'pretrained'
hello, i also meet this problem, did you solve that? I only use the model.pretrained only loads the weight of backbone
