### ISSUE TITLE
Custom Dataset Training Runtime error

### ISSUE THREAD

**Issue by HelyModi** [SwinTransformer/Swin-Transformer-Object-Detection#8]
Hi all,

I am getting this error while running the tools/train.py file on Google Colab.
"RuntimeError: Default process group has not been initialized, please make sure to call init_process_group."

I do not know how to approach this issue. Any help will be appreciated. Thanks!

**Comment by chrisjuniorli** [comment]
I would recommend using tools/dist_train.sh, since the default setting is designed for multi-gpu training

**Comment by impiga** [comment]
Hi, @HelyModi
Could you share the command you ran and the error trackback?

**Comment by HelyModi** [comment]
> Could you share the command you ran and the error trackback?

I ran this command:
**!python tools/train.py {config_fname}**

I get the following error:
2021-04-19 13:13:03,040 - mmdet - INFO - Start running, host: root@96e32ce1b7c6, work_dir: /content/drive/MyDrive/mmdetection_object_detection_demo/Swin-Transformer-Object-Detection/model_1
2021-04-19 13:13:03,041 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 185, in main
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/roi_heads/cascade_roi_head.py", line 259, in forward_train
    rcnn_train_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/roi_heads/cascade_roi_head.py", line 157, in _bbox_forward_train
    bbox_results = self._bbox_forward(stage, x, rois)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/roi_heads/cascade_roi_head.py", line 147, in _bbox_forward
    cls_score, bbox_pred = bbox_head(bbox_feats)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py", line 139, in forward
    x = conv(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/bricks/conv_module.py", line 200, in forward
    x = self.norm(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/batchnorm.py", line 532, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 711, in get_world_size
    return _get_group_size(group)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 263, in _get_group_size
    default_pg = _get_default_group()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
**RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.**

**Comment by HelyModi** [comment]
> I would recommend using tools/dist_train.sh, since the default setting is designed for multi-gpu training

Hi @chrisjuniorli , thanks for your recommendation. It worked!
