### ISSUE TITLE
Unexpected keyword argument 'ape', 'use_checkpoint'

### ISSUE THREAD

**Issue by wenchima** [SwinTransformer/Swin-Transformer-Object-Detection#92]
I tried to do the inference test with the command 

`python tools/test.py ./configs/swin/mask_rcnn_swin_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco.py ./checkpoints/mask_rcnn_swin_tiny_patch4_window7.pth --eval bbox segm`

But I always got the following Traceback as below.
loading annotations into memory...
Done (t=0.29s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'ape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/mask_rcnn.py", line 27, in __init__
    init_cfg=init_cfg)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'ape'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 173, in main
    model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wma/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MaskRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'ape'
```
I think the problems come from the mismatch of the keyword definition between the mmcv, mmdet packages and the configuration files. There are at least "embed_dim", "ape", and "use_checkpoint" that can not be recognized by the two packages above. It is easy to figure the "embed_dim" out which should be "embed_dims". But what about the other two?

Please provide me with some possible solutions to this problem. 

Thank you!

**Comment by SuhZhang** [comment]
> Nope, I have not figured it out although I tried to install the latest mmcv, mmdet packages. Please share any idea or solution if possible.

Hi, I have solved the problem by run `python setup.py develop` in Swin-Transformer-Object-Detection folder, you can refer to [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/84#issuecomment-914942193). But I still meet some strange situation [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/issues/97#issue-1026331344), please give me any suggestion.

**Comment by hplegend** [comment]
> @wenchima It doesn't work for me either. First, it happened with `embed_dim`, which I changed to `embed_dims`. Now the keyword `ape` has a problem. I tried to delete the `ape` parameter from the config file, then it threw an error for the `use_checkpoint` parameter.


well,  you solved it or not finally ? can you  share the solution experience?

**Comment by Money-HY** [comment]
The swin_transformer backbone in this program has a few differences between the one in mmdetection so you cannot just use the config file in this program.

**Comment by asluborski98** [comment]
I am getting the same error regarding `ape` are we suppose to use the MMDet repo? They don't have the updated configs and they have a different format.

**Comment by Lorenzo23** [comment]
I'm facing the same error regarding `ape` keyword, did anyone succeed to solve the issue?
